-- Tilpasser tabellerne så de passer til appen. Kør filen mod lifemaxxing databasen.
-- Kan køres flere gange uden at gå i stykker.

-- Auto-id på alle tabeller appen skriver i
DO $$
DECLARE
    t RECORD;
BEGIN
    FOR t IN SELECT * FROM (VALUES
        ('bruger', 'bruger_id'),
        ('fitness_maal', 'maal_id'),
        ('delmaal', 'delmaal_id'),
        ('traenings_praeference', 'praeference_id'),
        ('fitness_program', 'program_id'),
        ('makro_plan', 'makro_plan_id'),
        ('makro_justering', 'justering_id'),
        ('vejning', 'vejning_id'),
        ('traenings_plan', 'plan_id'),
        ('traenings_uge', 'uge_id'),
        ('traenings_dag', 'dag_id'),
        ('planlagt_ovelse', 'planlagt_ovelse_id'),
        ('ovelse', 'ovelse_id'),
        ('traenings_pas', 'pas_id'),
        ('logget_saet', 'logget_saet_id'),
        ('personlig_rekord', 'rekord_id')
    ) AS v(tabel, kolonne)
    LOOP
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_name = t.tabel AND column_name = t.kolonne AND is_identity = 'YES') THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY', t.tabel, t.kolonne);
        END IF;
        -- Sørger for at næste id ligger efter dem der allerede findes (fx øvelserne)
        EXECUTE format('SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE((SELECT MAX(%I) FROM %I), 0) + 1, false)',
                       t.tabel, t.kolonne, t.kolonne, t.tabel);
    END LOOP;
END $$;

-- Login
ALTER TABLE bruger ADD COLUMN IF NOT EXISTS brugernavn VARCHAR(20) UNIQUE;
ALTER TABLE bruger ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE bruger ALTER COLUMN brugernavn SET NOT NULL;
ALTER TABLE bruger ALTER COLUMN password_hash SET NOT NULL;

-- Profil. Alder gemmes som foedselsdato, vægten ligger i vejning
ALTER TABLE bruger_profil ADD COLUMN IF NOT EXISTS skader TEXT;

-- Svarene fra spørgeskemaet om træning
ALTER TABLE traenings_praeference ADD COLUMN IF NOT EXISTS fokus VARCHAR(30);
ALTER TABLE traenings_praeference ADD COLUMN IF NOT EXISTS traeningsstil VARCHAR(30);
ALTER TABLE traenings_praeference ADD COLUMN IF NOT EXISTS vil_styrke BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE traenings_praeference ADD COLUMN IF NOT EXISTS vil_cardio BOOLEAN NOT NULL DEFAULT FALSE;

-- Målet. De fysiske delmål (Stærkere, Eksplosiv osv.) ligger i delmaal
ALTER TABLE fitness_maal ADD COLUMN IF NOT EXISTS start_vaegt_kg NUMERIC(5,1);
ALTER TABLE fitness_maal ADD COLUMN IF NOT EXISTS maal_vaegt_kg NUMERIC(5,1);
ALTER TABLE fitness_maal ADD COLUMN IF NOT EXISTS ugentlig_aendring_kg NUMERIC(4,2);

-- Forklaringen på hvordan makroerne er regnet ud
ALTER TABLE makro_plan ADD COLUMN IF NOT EXISTS beregning TEXT;

-- Cardio og HIIT har tid i stedet for sæt og reps (dosering står på ovelse)
ALTER TABLE planlagt_ovelse ALTER COLUMN saet DROP NOT NULL;
ALTER TABLE planlagt_ovelse ALTER COLUMN reps_min DROP NOT NULL;
